# Generated by Django 5.0.3 on 2024-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0002_alter_customuser_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('link_tes', models.CharField(max_length=10)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
