# Generated by Django 5.0.3 on 2024-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0007_remove_subkriteria_kriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='subkriteria',
            name='kriteria',
            field=models.ManyToManyField(to='spk_app.kriteria'),
        ),
    ]
