# Generated by Django 5.0.3 on 2024-04-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0008_subkriteria_kriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kriteria',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='subkriteria',
            name='kriteria',
        ),
        migrations.AddField(
            model_name='subkriteria',
            name='kriteria',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='spk_app.kriteria'),
            preserve_default=False,
        ),
    ]
