# Generated by Django 5.0.3 on 2024-04-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0009_alter_kriteria_nama_remove_subkriteria_kriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subkriteria',
            name='kriteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subkriteria', to='spk_app.kriteria'),
        ),
    ]
