# Generated by Django 5.0.3 on 2024-04-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0010_alter_subkriteria_kriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='gap',
            field=models.IntegerField(default=0),
        ),
    ]
