# Generated by Django 5.0.3 on 2024-04-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0011_kriteria_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='kriteria',
            name='factor',
            field=models.CharField(default='CF & SF', max_length=100),
        ),
    ]
