# Generated by Django 5.0.3 on 2024-04-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0012_kriteria_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selisih', models.IntegerField()),
                ('bobot', models.IntegerField()),
                ('nilai', models.IntegerField()),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
    ]
