# Generated by Django 5.0.3 on 2024-04-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0013_botot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botot',
            name='nilai',
            field=models.FloatField(),
        ),
    ]
