# Generated by Django 5.0.3 on 2024-04-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0014_alter_botot_nilai'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Botot',
            new_name='Bobot',
        ),
    ]
