# Generated by Django 4.2.6 on 2024-04-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0016_penilaian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaian',
            name='kriteria1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria1', to='spk_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='kriteria2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria2', to='spk_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='kriteria3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria3', to='spk_app.subkriteria'),
        ),
        migrations.AlterField(
            model_name='penilaian',
            name='kriteria4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kriteria4', to='spk_app.subkriteria'),
        ),
    ]
