# Generated by Django 5.0.3 on 2024-04-19 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0018_penilaiangap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaiangap',
            name='alternatif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_app.alternatif'),
        ),
    ]
