# Generated by Django 5.0.3 on 2024-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0019_alter_penilaiangap_alternatif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaiangap',
            name='kriteria1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penilaiangap',
            name='kriteria2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penilaiangap',
            name='kriteria3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='penilaiangap',
            name='kriteria4',
            field=models.IntegerField(),
        ),
    ]
