# Generated by Django 5.0.3 on 2024-04-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0020_alter_penilaiangap_kriteria1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianRangking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kriteria1', models.IntegerField()),
                ('kriteria2', models.IntegerField()),
                ('kriteria3', models.IntegerField()),
                ('kriteria4', models.IntegerField()),
                ('ncf', models.FloatField()),
                ('nsf', models.FloatField()),
                ('hasil', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_app.alternatif')),
            ],
        ),
    ]
