# Generated by Django 5.0.3 on 2024-04-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0021_penilaianrangking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianrangking',
            name='hasil',
        ),
        migrations.RemoveField(
            model_name='penilaianrangking',
            name='ncf',
        ),
        migrations.RemoveField(
            model_name='penilaianrangking',
            name='nsf',
        ),
    ]
