# Generated by Django 5.0.3 on 2024-04-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0022_remove_penilaianrangking_hasil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penilaianrangking',
            name='kriteria1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penilaianrangking',
            name='kriteria2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penilaianrangking',
            name='kriteria3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penilaianrangking',
            name='kriteria4',
            field=models.FloatField(),
        ),
    ]
