# Generated by Django 5.0.3 on 2024-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0023_alter_penilaianrangking_kriteria1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianrangking',
            name='ncf',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='penilaianrangking',
            name='nsf',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
