# Generated by Django 5.0.3 on 2024-04-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0024_penilaianrangking_ncf_penilaianrangking_nsf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaianrangking',
            name='ncf',
        ),
        migrations.RemoveField(
            model_name='penilaianrangking',
            name='nsf',
        ),
    ]
