# Generated by Django 5.0.3 on 2024-04-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0025_remove_penilaianrangking_ncf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianHasil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf', models.FloatField()),
                ('nsf', models.FloatField()),
                ('alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spk_app.alternatif')),
            ],
        ),
    ]
