# Generated by Django 5.0.3 on 2024-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk_app', '0027_kriteria_persentase'),
    ]

    operations = [
        migrations.AddField(
            model_name='penilaianhasil',
            name='hasil',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
